default: &default
  adapter: postgresql
  encoding: unicode
  username: socki
  password: "<%= ENV['SOCKI_DATABASE_PASSWORD'] %>"
  host: localhost
  pool: 5

development:
  <<: *default
  database: socki_development

test:
  <<: *default
  database: socki_test

production:
  <<: *default
  database: socki_production
  username: socki
  password: "<%= ENV['SOCKI_DATABASE_PASSWORD'] %>"
